export default function handler(req, res) {
  res.status(200).json({
    fEstado_Ordenes_Servicio: [
      {
        Id_Agencia: 305,
        Folio_Orden_Reparacion: 100035571,
        Estado_Orden: "TERMINADO",
        Linea: "YARIS",
      },
      {
        Id_Agencia: 401,
        Folio_Orden_Reparacion: 10006271,
        Estado_Orden: "CERRADA/FACTURADA",
        Color: "BLANCO",
        Placas: "ELD1351",
      },
      {
        Id_Agencia: 115,
        Folio_Orden_Reparacion: 10065031,
        Estado_Orden: "CERRADA/FACTURADA",
        Linea: "YARIS",
        Placas: "SUF3997",
      },
      {
        Id_Agencia: 115,
        Folio_Orden_Reparacion: 10065031,
        Estado_Orden: "CERRADA/FACTURADA",
        Linea: "YARIS",
        Placas: "SUF3997",
        Color: "BLANCO",
      },
      {
        Id_Agencia: 115,
        Folio_Orden_Reparacion: 10065032,
        Estado_Orden: "CERRADA/FACTURADA",
        Linea: "YARIS",
        Placas: "SUF3997",
      },
      {
        Id_Agencia: 110,
        Folio_Orden_Reparacion: 100663251,
        Estado_Orden: "CERRADA/FACTURADA",
        Linea: "SENTRA",
        Color: "GRIS",
        Placas: "STP6489",
      },
      {
        Id_Agencia: 110,
        Folio_Orden_Reparacion: 100663251,
        Estado_Orden: "PENDIENTE DE PIEZA",
        Linea: "SENTRA",
        Color: "GRIS",
        Placas: "STP6489",
      },
      {
        Id_Agencia: 110,
        Folio_Orden_Reparacion: 100663251,
        Estado_Orden: "TERMINADO",
        Linea: "SENTRA",
        Color: "GRIS",
        Placas: "STP6489",
      },
      {
        Id_Agencia: 110,
        Folio_Orden_Reparacion: 100663251,
        Estado_Orden: "UNIDAD EN RAMPA",
        Linea: "SENTRA",
        Color: "GRIS",
        Placas: "STP6489",
      },
      {
        Id_Agencia: 110,
        Folio_Orden_Reparacion: 100663252,
        Estado_Orden: "CERRADA/FACTURADA",
        Linea: "SENTRA",
        Color: "GRIS",
        Placas: "STP6489",
      },
      {
        Id_Agencia: 110,
        Folio_Orden_Reparacion: 100663252,
        Estado_Orden: "EN ESPERA",
        Linea: "SENTRA",
        Color: "GRIS",
        Placas: "STP6489",
      },
      {
        Id_Agencia: 110,
        Folio_Orden_Reparacion: 100663252,
        Estado_Orden: "UNIDAD EN RAMPA",
        Linea: "SENTRA",
        Color: "GRIS",
        Placas: "STP6489",
      },
      {
        Id_Agencia: 402,
        Folio_Orden_Reparacion: 100663281,
        Estado_Orden: "CERRADA/FACTURADA",
        Linea: "HRV TOURING 2018",
        Color: "PLATA LUNAR",
        Placas: "Jan-39",
      },
      {
        Id_Agencia: 402,
        Folio_Orden_Reparacion: 100663281,
        Estado_Orden: "EN ESPERA",
        Linea: "HRV TOURING 2018",
        Color: "PLATA LUNAR",
        Placas: "Jan-39",
      },
      {
        Id_Agencia: 402,
        Folio_Orden_Reparacion: 100663281,
        Estado_Orden: "TERMINADO",
        Linea: "HRV TOURING 2018",
        Color: "PLATA LUNAR",
        Placas: "Jan-39",
      },
      {
        Id_Agencia: 401,
        Folio_Orden_Reparacion: 100663321,
        Estado_Orden: "CERRADA/FACTURADA",
        Linea: "FIT HIT CVT 2019",
        Color: "NEGRO CRISTAL",
        Placas: "EMY3476",
      },
      {
        Id_Agencia: 401,
        Folio_Orden_Reparacion: 100663321,
        Estado_Orden: "EN ESPERA",
        Linea: "FIT HIT CVT 2019",
        Color: "NEGRO CRISTAL",
        Placas: "EMY3476",
      },
      {
        Id_Agencia: 401,
        Folio_Orden_Reparacion: 100663321,
        Estado_Orden: "PROCESO TERMINADO",
        Linea: "FIT HIT CVT 2019",
        Color: "NEGRO CRISTAL",
        Placas: "EMY3476",
      },
      {
        Id_Agencia: 401,
        Folio_Orden_Reparacion: 100663321,
        Estado_Orden: "TERMINADO",
        Linea: "FIT HIT CVT 2019",
        Color: "NEGRO CRISTAL",
        Placas: "EMY3476",
      },
      {
        Id_Agencia: 104,
        Folio_Orden_Reparacion: 100663351,
        Estado_Orden: "CERRADA/FACTURADA",
        Linea: "HRV UNIQ MT 2019",
        Color: "BLANCO PLATINO",
        Placas: "RZX423A",
      },
      {
        Id_Agencia: 104,
        Folio_Orden_Reparacion: 100663351,
        Estado_Orden: "UNIDAD EN RAMPA",
        Linea: "HRV UNIQ MT 2019",
        Color: "BLANCO PLATINO",
        Placas: "RZX423A",
      },
      {
        Id_Agencia: 104,
        Folio_Orden_Reparacion: 100663352,
        Estado_Orden: "CERRADA/FACTURADA",
        Linea: "HRV UNIQ MT 2019",
        Color: "BLANCO PLATINO",
        Placas: "RZX423A",
      },
      {
        Id_Agencia: 104,
        Folio_Orden_Reparacion: 100663352,
        Estado_Orden: "TERMINADO",
        Linea: "HRV UNIQ MT 2019",
        Color: "BLANCO PLATINO",
        Placas: "RZX423A",
      },
      {
        Id_Agencia: 104,
        Folio_Orden_Reparacion: 100663352,
        Estado_Orden: "UNIDAD EN RAMPA",
        Linea: "HRV UNIQ MT 2019",
        Color: "BLANCO PLATINO",
        Placas: "RZX423A",
      },
      {
        Id_Agencia: 111,
        Folio_Orden_Reparacion: 100663411,
        Estado_Orden: "CERRADA/FACTURADA",
        Linea: "VERSA",
        Color: "BLANCO",
        Placas: "SEW092A",
      },
      {
        Id_Agencia: 111,
        Folio_Orden_Reparacion: 100663411,
        Estado_Orden: "PENDIENTE DE PIEZA",
        Linea: "VERSA",
        Color: "BLANCO",
        Placas: "SEW092A",
      },
      {
        Id_Agencia: 111,
        Folio_Orden_Reparacion: 100663411,
        Estado_Orden: "TERMINADO",
        Linea: "VERSA",
        Color: "BLANCO",
        Placas: "SEW092A",
      },
      {
        Id_Agencia: 109,
        Folio_Orden_Reparacion: 100663491,
        Estado_Orden: "CERRADA/FACTURADA",
        Linea: "VERSA ADVANCE TM 1.6 LTS",
        Color: "GRIS",
        Placas: "STK587A",
      },
      {
        Id_Agencia: 105,
        Folio_Orden_Reparacion: 100663511,
        Estado_Orden: "CERRADA/FACTURADA",
        Linea: "ACURA MDX SH-AWD 5 PTS AUT 2018",
        Color: "BLANCO DIAMANTE",
        Placas: "STD722A",
      },
      {
        Id_Agencia: 400,
        Folio_Orden_Reparacion: 100663591,
        Estado_Orden: "CERRADA/FACTURADA",
        Linea: "CIVIC I-STYLE 2019",
        Color: "ACERO",
        Placas: "ENM2613",
      },
      {
        Id_Agencia: 400,
        Folio_Orden_Reparacion: 100663591,
        Estado_Orden: "EN ESPERA",
        Linea: "CIVIC I-STYLE 2019",
        Color: "ACERO",
        Placas: "ENM2613",
      },
      {
        Id_Agencia: 110,
        Folio_Orden_Reparacion: 100663771,
        Estado_Orden: "CERRADA/FACTURADA",
        Linea: "MARCH SENSE T/MAN",
        Color: "LUNAR",
      },
      {
        Id_Agencia: 104,
        Folio_Orden_Reparacion: 100663941,
        Estado_Orden: "CERRADA/FACTURADA",
        Linea: "CRV TURBO PLUS CVT 2019",
        Color: "NEGRO CRISTAL",
        Placas: "SAE158A",
      },
      {
        Id_Agencia: 104,
        Folio_Orden_Reparacion: 100663942,
        Estado_Orden: "CERRADA/FACTURADA",
        Linea: "CRV TURBO PLUS CVT 2019",
        Color: "NEGRO CRISTAL",
        Placas: "SAE158A",
      },
      {
        Id_Agencia: 102,
        Folio_Orden_Reparacion: 100664261,
        Estado_Orden: "CERRADA/FACTURADA",
        Linea: "FIT HIT CVT 2019",
        Color: "ACERO",
        Placas: "RZC148A",
      },
      {
        Id_Agencia: 102,
        Folio_Orden_Reparacion: 100664261,
        Estado_Orden: "EN ESPERA",
        Linea: "FIT HIT CVT 2019",
        Color: "ACERO",
        Placas: "RZC148A",
      },
      {
        Id_Agencia: 200,
        Folio_Orden_Reparacion: 100664281,
        Estado_Orden: "CERRADA/FACTURADA",
        Linea: "CIVIC SEDAN",
      },
      {
        Id_Agencia: 200,
        Folio_Orden_Reparacion: 100664281,
        Estado_Orden: "EN ESPERA",
        Linea: "CIVIC SEDAN",
      },
      {
        Id_Agencia: 200,
        Folio_Orden_Reparacion: 100664281,
        Estado_Orden: "TERMINADO",
        Linea: "CIVIC SEDAN",
      },
      {
        Id_Agencia: 110,
        Folio_Orden_Reparacion: 100664391,
        Estado_Orden: "CERRADA/FACTURADA",
        Linea: "ALTIMA 2017 BLANCO",
        Color: "BLANCO",
        Placas: "RNF506A",
      },
      {
        Id_Agencia: 110,
        Folio_Orden_Reparacion: 100664391,
        Estado_Orden: "PASA A LAVADO",
        Linea: "ALTIMA 2017 BLANCO",
        Color: "BLANCO",
        Placas: "RNF506A",
      },
      {
        Id_Agencia: 110,
        Folio_Orden_Reparacion: 100664501,
        Estado_Orden: "CERRADA/FACTURADA",
        Linea: "V.DRIVE T/M AC 1.6 LTS",
        Color: "HIERRO",
      },
      {
        Id_Agencia: 111,
        Folio_Orden_Reparacion: 100664681,
        Estado_Orden: "CERRADA/FACTURADA",
        Linea: "VERSA SENSE T/A AC 1.6L",
        Color: "AZUL",
        Placas: "SDM895A",
      },
      {
        Id_Agencia: 118,
        Folio_Orden_Reparacion: 100664701,
        Estado_Orden: "CERRADA/FACTURADA",
        Linea: "NEW SPORTAGE 2.4L SXL T/A (BLACK)",
        Color: "SNOW PEARL WHITE",
      },
      {
        Id_Agencia: 201,
        Folio_Orden_Reparacion: 100664721,
        Estado_Orden: "CERRADA/FACTURADA",
        Linea: "NEW KIA RIO 1.6L EX T/M SEDAN",
        Color: "SMOKE BLUE",
      },
      {
        Id_Agencia: 201,
        Folio_Orden_Reparacion: 100664722,
        Estado_Orden: "CERRADA/FACTURADA",
        Linea: "NEW KIA RIO 1.6L EX T/M SEDAN",
        Color: "SMOKE BLUE",
      },
      {
        Id_Agencia: 101,
        Folio_Orden_Reparacion: 100664781,
        Estado_Orden: "CERRADA/FACTURADA",
        Linea: "CRV TOURING CVT 2019",
        Color: "AZUL OBSIDIANA",
        Placas: "RZB646A",
      },
      {
        Id_Agencia: 101,
        Folio_Orden_Reparacion: 100664781,
        Estado_Orden: "PENDIENTE POR CANCELAR",
        Linea: "CRV TOURING CVT 2019",
        Color: "AZUL OBSIDIANA",
        Placas: "RZB646A",
      },
      {
        Id_Agencia: 101,
        Folio_Orden_Reparacion: 100664782,
        Estado_Orden: "CERRADA/FACTURADA",
        Linea: "CRV TOURING CVT 2019",
        Color: "AZUL OBSIDIANA",
        Placas: "RZB646A",
      },
      {
        Id_Agencia: 101,
        Folio_Orden_Reparacion: 100664782,
        Estado_Orden: "EN ESPERA",
        Linea: "CRV TOURING CVT 2019",
        Color: "AZUL OBSIDIANA",
        Placas: "RZB646A",
      },
      {
        Id_Agencia: 101,
        Folio_Orden_Reparacion: 100664782,
        Estado_Orden: "TERMINADO",
        Linea: "CRV TOURING CVT 2019",
        Color: "AZUL OBSIDIANA",
        Placas: "RZB646A",
      },
      {
        Id_Agencia: 101,
        Folio_Orden_Reparacion: 100664783,
        Estado_Orden: "CERRADA/FACTURADA",
        Linea: "CRV TOURING CVT 2019",
        Color: "AZUL OBSIDIANA",
        Placas: "RZB646A",
      },
      {
        Id_Agencia: 101,
        Folio_Orden_Reparacion: 100664783,
        Estado_Orden: "EN ESPERA",
        Linea: "CRV TOURING CVT 2019",
        Color: "AZUL OBSIDIANA",
        Placas: "RZB646A",
      },
      {
        Id_Agencia: 300,
        Folio_Orden_Reparacion: 100664801,
        Estado_Orden: "CERRADA/FACTURADA",
        Linea: "CRV EX 2019",
        Color: "PLATA LUNAR",
        Placas: "XET167A",
      },
      {
        Id_Agencia: 300,
        Folio_Orden_Reparacion: 100664802,
        Estado_Orden: "CERRADA/FACTURADA",
        Linea: "CRV EX 2019",
        Color: "PLATA LUNAR",
        Placas: "XET167A",
      },
      {
        Id_Agencia: 300,
        Folio_Orden_Reparacion: 100664802,
        Estado_Orden: "TERMINADO",
        Linea: "CRV EX 2019",
        Color: "PLATA LUNAR",
        Placas: "XET167A",
      },
      {
        Id_Agencia: 300,
        Folio_Orden_Reparacion: 100664802,
        Estado_Orden: "UNIDAD EN RAMPA",
        Linea: "CRV EX 2019",
        Color: "PLATA LUNAR",
        Placas: "XET167A",
      },
      {
        Id_Agencia: 201,
        Folio_Orden_Reparacion: 100664811,
        Estado_Orden: "CERRADA/FACTURADA",
        Linea: "NEW KIA RIO 1.6L EX T/M SEDAN",
        Color: "URBAN GRAY",
      },
      {
        Id_Agencia: 201,
        Folio_Orden_Reparacion: 100664971,
        Estado_Orden: "CERRADA/FACTURADA",
        Linea: 'FORTE PE 2.0L LX A/T SEDAN "SAM"',
        Color: "SNOW WHITE PEARL",
      },
      {
        Id_Agencia: 104,
        Folio_Orden_Reparacion: 100664991,
        Estado_Orden: "CERRADA/FACTURADA",
        Linea: "CRV EX",
        Color: "PLATA 2WD",
        Placas: "SSA2840",
      },
      {
        Id_Agencia: 104,
        Folio_Orden_Reparacion: 100664991,
        Estado_Orden: "TERMINADO",
        Linea: "CRV EX",
        Color: "PLATA 2WD",
        Placas: "SSA2840",
      },
      {
        Id_Agencia: 104,
        Folio_Orden_Reparacion: 100664991,
        Estado_Orden: "UNIDAD EN RAMPA",
        Linea: "CRV EX",
        Color: "PLATA 2WD",
        Placas: "SSA2840",
      },
      {
        Id_Agencia: 200,
        Folio_Orden_Reparacion: 100665131,
        Estado_Orden: "CERRADA/FACTURADA",
        Linea: "CRV TURBO PLUS 2020",
        Color: "PLATA LUNAR",
        Placas: "EXA990A",
      },
      {
        Id_Agencia: 200,
        Folio_Orden_Reparacion: 100665132,
        Estado_Orden: "CERRADA/FACTURADA",
        Linea: "CRV TURBO PLUS 2020",
        Color: "PLATA LUNAR",
        Placas: "EXA990A",
      },
      {
        Id_Agencia: 200,
        Folio_Orden_Reparacion: 100665132,
        Estado_Orden: "EN ESPERA",
        Linea: "CRV TURBO PLUS 2020",
        Color: "PLATA LUNAR",
        Placas: "EXA990A",
      },
      {
        Id_Agencia: 200,
        Folio_Orden_Reparacion: 100665132,
        Estado_Orden: "UNIDAD EN RAMPA",
        Linea: "CRV TURBO PLUS 2020",
        Color: "PLATA LUNAR",
        Placas: "EXA990A",
      },
      {
        Id_Agencia: 109,
        Folio_Orden_Reparacion: 100665151,
        Estado_Orden: "CERRADA/FACTURADA",
        Color: "BLANCO",
        Placas: "SUG3105",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665271,
        Estado_Orden: "CERRADA/FACTURADA",
        Linea: "TUCSON",
        Color: "BLANCO",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "CERRADA/FACTURADA",
        Linea: "TUCSON",
        Color: "BLANCO",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "EN ESPERA",
        Linea: "TUCSON",
        Color: "BLANCO",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "EN ESPERA",
        Linea: "Seltos 5 Door Wagon 1.6Lt DOHC 6 Speed Automatic",
        Color: "INFERNO RED+ BLACK ROOF",
        Placas: "XKB1690",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "EN ESPERA",
        Linea: "Seltos 5 Door Wagon 1.6Lt DOHC 6 Speed Automatic",
        Color: "INFERNO RED+ BLACK ROOF",
        Placas: "XKB1690",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "EN ESPERA",
        Linea: "Seltos 5 Door Wagon 1.6Lt DOHC 6 Speed Automatic",
        Color: "INFERNO RED+ BLACK ROOF",
        Placas: "XKB1690",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "EN ESPERA",
        Linea: "Seltos 5 Door Wagon 1.6Lt DOHC 6 Speed Automatic",
        Color: "INFERNO RED+ BLACK ROOF",
        Placas: "XKB1690",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "EN ESPERA",
        Linea: "Seltos 5 Door Wagon 1.6Lt DOHC 6 Speed Automatic",
        Color: "INFERNO RED+ BLACK ROOF",
        Placas: "XKB1690",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "EN ESPERA",
        Linea: "Seltos 5 Door Wagon 1.6Lt DOHC 6 Speed Automatic",
        Color: "INFERNO RED+ BLACK ROOF",
        Placas: "XKB1690",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "EN ESPERA",
        Linea: "Seltos 5 Door Wagon 1.6Lt DOHC 6 Speed Automatic",
        Color: "INFERNO RED+ BLACK ROOF",
        Placas: "XKB1690",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "EN ESPERA",
        Linea: "Seltos 5 Door Wagon 1.6Lt DOHC 6 Speed Automatic",
        Color: "INFERNO RED+ BLACK ROOF",
        Placas: "XKB1690",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "EN ESPERA",
        Linea: "Seltos 5 Door Wagon 1.6Lt DOHC 6 Speed Automatic",
        Color: "INFERNO RED+ BLACK ROOF",
        Placas: "XKB1690",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "EN ESPERA",
        Linea: "Seltos 5 Door Wagon 1.6Lt DOHC 6 Speed Automatic",
        Color: "INFERNO RED+ BLACK ROOF",
        Placas: "XKB1690",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "EN ESPERA",
        Linea: "Seltos 5 Door Wagon 1.6Lt DOHC 6 Speed Automatic",
        Color: "INFERNO RED+ BLACK ROOF",
        Placas: "XKB1690",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "EN ESPERA",
        Linea: "Seltos 5 Door Wagon 1.6Lt DOHC 6 Speed Automatic",
        Color: "INFERNO RED+ BLACK ROOF",
        Placas: "XKB1690",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "EN ESPERA",
        Linea: "Seltos 5 Door Wagon 1.6Lt DOHC 6 Speed Automatic",
        Color: "INFERNO RED+ BLACK ROOF",
        Placas: "XKB1690",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "EN ESPERA",
        Linea: "Seltos 5 Door Wagon 1.6Lt DOHC 6 Speed Automatic",
        Color: "INFERNO RED+ BLACK ROOF",
        Placas: "XKB1690",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "EN ESPERA",
        Linea: "Seltos 5 Door Wagon 1.6Lt DOHC 6 Speed Automatic",
        Color: "INFERNO RED+ BLACK ROOF",
        Placas: "XKB1690",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "EN ESPERA",
        Linea: "Seltos 5 Door Wagon 1.6Lt DOHC 6 Speed Automatic",
        Color: "INFERNO RED+ BLACK ROOF",
        Placas: "XKB1690",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "EN ESPERA",
        Linea: "Seltos 5 Door Wagon 1.6Lt DOHC 6 Speed Automatic",
        Color: "INFERNO RED+ BLACK ROOF",
        Placas: "XKB1690",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "EN ESPERA",
        Linea: "Seltos 5 Door Wagon 1.6Lt DOHC 6 Speed Automatic",
        Color: "INFERNO RED+ BLACK ROOF",
        Placas: "XKB1690",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "EN ESPERA",
        Linea: "Seltos 5 Door Wagon 1.6Lt DOHC 6 Speed Automatic",
        Color: "INFERNO RED+ BLACK ROOF",
        Placas: "XKB1690",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "EN ESPERA",
        Linea: "Seltos 5 Door Wagon 1.6Lt DOHC 6 Speed Automatic",
        Color: "INFERNO RED+ BLACK ROOF",
        Placas: "XKB1690",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "EN ESPERA",
        Linea: "Seltos 5 Door Wagon 1.6Lt DOHC 6 Speed Automatic",
        Color: "INFERNO RED+ BLACK ROOF",
        Placas: "XKB1690",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "EN ESPERA",
        Linea: "Seltos 5 Door Wagon 1.6Lt DOHC 6 Speed Automatic",
        Color: "INFERNO RED+ BLACK ROOF",
        Placas: "XKB1690",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "EN ESPERA",
        Linea: "Seltos 5 Door Wagon 1.6Lt DOHC 6 Speed Automatic",
        Color: "INFERNO RED+ BLACK ROOF",
        Placas: "XKB1690",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "EN ESPERA",
        Linea: "Seltos 5 Door Wagon 1.6Lt DOHC 6 Speed Automatic",
        Color: "INFERNO RED+ BLACK ROOF",
        Placas: "XKB1690",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "EN ESPERA",
        Linea: "Seltos 5 Door Wagon 1.6Lt DOHC 6 Speed Automatic",
        Color: "INFERNO RED+ BLACK ROOF",
        Placas: "XKB1690",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "EN ESPERA",
        Linea: "Seltos 5 Door Wagon 1.6Lt DOHC 6 Speed Automatic",
        Color: "INFERNO RED+ BLACK ROOF",
        Placas: "XKB1690",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "EN ESPERA",
        Linea: "Seltos 5 Door Wagon 1.6Lt DOHC 6 Speed Automatic",
        Color: "INFERNO RED+ BLACK ROOF",
        Placas: "XKB1690",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "EN ESPERA",
        Linea: "Seltos 5 Door Wagon 1.6Lt DOHC 6 Speed Automatic",
        Color: "INFERNO RED+ BLACK ROOF",
        Placas: "XKB1690",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "EN ESPERA",
        Linea: "Seltos 5 Door Wagon 1.6Lt DOHC 6 Speed Automatic",
        Color: "INFERNO RED+ BLACK ROOF",
        Placas: "XKB1690",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "EN ESPERA",
        Linea: "Seltos 5 Door Wagon 1.6Lt DOHC 6 Speed Automatic",
        Color: "INFERNO RED+ BLACK ROOF",
        Placas: "XKB1690",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "EN ESPERA",
        Linea: "Seltos 5 Door Wagon 1.6Lt DOHC 6 Speed Automatic",
        Color: "INFERNO RED+ BLACK ROOF",
        Placas: "XKB1690",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "EN ESPERA",
        Linea: "Seltos 5 Door Wagon 1.6Lt DOHC 6 Speed Automatic",
        Color: "INFERNO RED+ BLACK ROOF",
        Placas: "XKB1690",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "EN ESPERA",
        Linea: "Seltos 5 Door Wagon 1.6Lt DOHC 6 Speed Automatic",
        Color: "INFERNO RED+ BLACK ROOF",
        Placas: "XKB1690",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "EN ESPERA",
        Linea: "Seltos 5 Door Wagon 1.6Lt DOHC 6 Speed Automatic",
        Color: "INFERNO RED+ BLACK ROOF",
        Placas: "XKB1690",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "EN ESPERA",
        Linea: "Seltos 5 Door Wagon 1.6Lt DOHC 6 Speed Automatic",
        Color: "INFERNO RED+ BLACK ROOF",
        Placas: "XKB1690",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "EN ESPERA",
        Linea: "Seltos 5 Door Wagon 1.6Lt DOHC 6 Speed Automatic",
        Color: "INFERNO RED+ BLACK ROOF",
        Placas: "XKB1690",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "EN ESPERA",
        Linea: "Seltos 5 Door Wagon 1.6Lt DOHC 6 Speed Automatic",
        Color: "INFERNO RED+ BLACK ROOF",
        Placas: "XKB1690",
      },
      {
        Id_Agencia: 113,
        Folio_Orden_Reparacion: 100665272,
        Estado_Orden: "EN ESPERA",
        Linea: "Seltos 5 Door Wagon 1.6Lt DOHC 6 Speed Automatic",
        Color: "INFERNO RED+ BLACK ROOF",
        Placas: "XKB1690",
      },
    ],
  });
}
